### ISSUE TITLE
Obtained incorrect `best_veriied_block` by calling the `get_best_veriied_block` API interface

### ISSUE THREAD

**Issue by renmengkai** [bestinslot-xyz/OPI-LC#9]
when request url : `https://api.opi.network/lc/get_best_verified_block?event_hash_version=2`
we got reponse : `{"error":false,"data":{"best_verified_block":"2587900"}}`
case :
![image](https://github.com/bestinslot-xyz/OPI-LC/assets/31378513/c58da854-5860-47b2-a765-6a6b29d5fb62)

**Comment by samedcildir** [comment]
this is fixed a while ago, sorry for late reply
